import React from 'react'
import Key from '@/app/components/key/key'  
export default function KeyboardPage() {
    const keys = [
      { id: 1, keyword: 'esc' },
      { id: 2, keyword: 'f1' },
      { id: 3, keyword: 'f2' },
      { id: 4, keyword: 'f3' },
      { id: 5, keyword: 'f4' },
        { id: 6, keyword: 'f5' },
        { id: 7, keyword: 'f6' },
        { id: 8, keyword: 'f7' },
        { id: 9, keyword: 'f8' },
        { id: 10, keyword: 'f9' },
        { id: 11, keyword: 'f10' },
        { id: 12, keyword: 'f11' },
        { id: 13, keyword: 'f12' },
        { id: 14, keyword: 'prt sc' },
        { id: 15, keyword: 'del' },
        { id: 16, keyword: '`' },
        { id: 17, keyword: '1' },
        { id: 18, keyword: '2' },
        { id: 19, keyword: '3' },
        { id: 20, keyword: '4' },
        { id: 21, keyword: '5' },
        { id: 22, keyword: '6' },
        { id: 23, keyword: '7' },
        { id: 24, keyword: '8' },
        { id: 25, keyword: '9' },
        { id: 26, keyword: '0' },
        { id: 27, keyword: '-' },
        { id: 28, keyword: '=' },
        { id: 29, keyword: 'backspace' },
        { id: 30, keyword: 'tab' },
        { id: 31, keyword: 'q' },
        { id: 32, keyword: 'w' },
        { id: 33, keyword: 'e' },
        { id: 34, keyword: 'r' },
        { id: 35, keyword: 't' },
        { id: 36, keyword: 'y' },
        { id: 37, keyword: 'u' },
        { id: 38, keyword: 'i' },
        { id: 39, keyword: 'o' },
        { id: 40, keyword: 'p' },
        { id: 41, keyword: '[' },
        { id: 42, keyword: ']' },
        { id: 43, keyword: '\\' },
        { id: 44, keyword: 'caps lock' },
        { id: 45, keyword: 'a' },
        { id: 46, keyword: 's' },
        { id: 47, keyword: 'd' },
        { id: 48, keyword: 'f' },
        { id: 49, keyword: 'g' },
        { id: 50, keyword: 'h' },
        { id: 51, keyword: 'j' },
        { id: 52, keyword: 'k' },
        { id: 53, keyword: 'l' },
        { id: 54, keyword: ';' },
        { id: 55, keyword: '\'' },
        { id: 56, keyword: 'enter' },
        { id: 57, keyword: 'shift' },
        { id: 58, keyword: 'z' },
        { id: 59, keyword: 'x' },
        { id: 60, keyword: 'c' },
        { id: 61, keyword: 'v' },
        { id: 62, keyword: 'b' },
        { id: 63, keyword: 'n' },
        { id: 64, keyword: 'm' },
        { id: 65, keyword: ',' },
        { id: 66, keyword: '.' },
        { id: 67, keyword: '/' },
        { id: 68, keyword: 'shift' },
        { id: 69, keyword: 'ctrl' },
        { id: 70, keyword: 'win' },
        { id: 71, keyword: 'alt' },
        { id: 75, keyword: 'Cmd' },
        { id: 72, keyword: 'space' },
        { id: 73, keyword: 'alt' },
        { id: 74, keyword: 'fn' },
        { id: 76, keyword: 'ctrl' },
        
    ]
  return (
    <div  className='bg-neutral-900 max-w-6xl mx-auto p-4 rounded-lg mt-10 flex flex-wrap gap-2 justify-center align-center'>
      {keys.map(key => (
        <Key key={key.id} keyword={key.keyword}  />
      ))}
    </div>
  )
}
